// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lights.proto

package lights;

public interface BrightnessRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lights.BrightnessRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 lights = 1;</code>
   */
  int getLights();
}
