// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lights.proto

package lights;

public final class LightsImpl {
  private LightsImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lights_PowerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lights_PowerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lights_PowerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lights_PowerResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lights_BrightnessRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lights_BrightnessRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_lights_BrightnessResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_lights_BrightnessResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014lights.proto\022\006lights\"\035\n\014PowerRequest\022\r" +
      "\n\005power\030\001 \001(\010\"\036\n\rPowerResponse\022\r\n\005power\030" +
      "\001 \001(\010\"#\n\021BrightnessRequest\022\016\n\006lights\030\001 \001" +
      "(\005\"$\n\022BrightnessResponse\022\016\n\006lights\030\001 \001(\005" +
      "2\227\001\n\014LightService\022<\n\013powerSwitch\022\024.light" +
      "s.PowerRequest\032\025.lights.PowerResponse\"\000\022" +
      "I\n\nbrightness\022\031.lights.BrightnessRequest" +
      "\032\032.lights.BrightnessResponse\"\000(\0010\001B\026\n\006li" +
      "ghtsB\nLightsImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_lights_PowerRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_lights_PowerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lights_PowerRequest_descriptor,
        new java.lang.String[] { "Power", });
    internal_static_lights_PowerResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_lights_PowerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lights_PowerResponse_descriptor,
        new java.lang.String[] { "Power", });
    internal_static_lights_BrightnessRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_lights_BrightnessRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lights_BrightnessRequest_descriptor,
        new java.lang.String[] { "Lights", });
    internal_static_lights_BrightnessResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_lights_BrightnessResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_lights_BrightnessResponse_descriptor,
        new java.lang.String[] { "Lights", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
