// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lights.proto

package lights;

public interface PowerResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lights.PowerResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool power = 1;</code>
   */
  boolean getPower();
}
