// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: thermometer.proto

package thermometer;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:thermometer.Empty)
    com.google.protobuf.MessageOrBuilder {
}
