// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package thermometer;

public interface PowerResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:thermometer.PowerResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool power = 1;</code>
   */
  boolean getPower();
}
