// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: thermometer.proto

package thermometer;

public interface TempRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:thermometer.TempRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 temperature = 1;</code>
   */
  int getTemperature();
}
