// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: thermometer.proto

package thermometer;

public interface TempResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:thermometer.TempResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string temperature = 1;</code>
   */
  java.lang.String getTemperature();
  /**
   * <code>string temperature = 1;</code>
   */
  com.google.protobuf.ByteString
      getTemperatureBytes();
}
