// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package thermometer;

public interface TemperatureRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:thermometer.TemperatureRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 temperature = 1;</code>
   */
  int getTemperature();
}
