// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aircon.proto

package aircon;

public interface AdjustTempRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:aircon.AdjustTempRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 adjust = 1;</code>
   */
  int getAdjust();
}
