// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aircon.proto

package aircon;

public final class AirconImpl {
  private AirconImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aircon_PowerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aircon_PowerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aircon_PowerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aircon_PowerResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aircon_AdjustTempRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aircon_AdjustTempRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_aircon_AdjustTempResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_aircon_AdjustTempResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014aircon.proto\022\006aircon\"\035\n\014PowerRequest\022\r" +
      "\n\005power\030\001 \001(\010\"\036\n\rPowerResponse\022\r\n\005power\030" +
      "\001 \001(\010\"#\n\021AdjustTempRequest\022\016\n\006adjust\030\001 \001" +
      "(\005\"$\n\022AdjustTempResponse\022\016\n\006adjust\030\001 \001(\005" +
      "2\226\001\n\rAirconService\022<\n\013powerSwitch\022\024.airc" +
      "on.PowerRequest\032\025.aircon.PowerResponse\"\000" +
      "\022G\n\ngetHeating\022\031.aircon.AdjustTempReques" +
      "t\032\032.aircon.AdjustTempResponse\"\000(\001B\026\n\006air" +
      "conB\nAirconImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_aircon_PowerRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_aircon_PowerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aircon_PowerRequest_descriptor,
        new java.lang.String[] { "Power", });
    internal_static_aircon_PowerResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_aircon_PowerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aircon_PowerResponse_descriptor,
        new java.lang.String[] { "Power", });
    internal_static_aircon_AdjustTempRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_aircon_AdjustTempRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aircon_AdjustTempRequest_descriptor,
        new java.lang.String[] { "Adjust", });
    internal_static_aircon_AdjustTempResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_aircon_AdjustTempResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_aircon_AdjustTempResponse_descriptor,
        new java.lang.String[] { "Adjust", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
