// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aircon.proto

package aircon;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:aircon.Empty)
    com.google.protobuf.MessageOrBuilder {
}
