// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aircon.proto

package aircon;

public interface PowerRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:aircon.PowerRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool power = 1;</code>
   */
  boolean getPower();
}
